// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as route$0 from "../route/models.js";

/**
 * Config 是 config.json 的运行时配置，位于程序执行目录。
 * 
 * 优先级：命令行旗标 > config.json > 默认值。配置文件只在启动/显式保存时
 * 读取（v0.5.24 起取消运行中热加载——避免外部编辑与 GUI 保存相互覆盖）。
 */
export class Config {
    /**
     * ListenAddr 是 mixed HTTP+SOCKS5 代理的监听地址。
     */
    "listen_addr": string;

    /**
     * EdgeAddr 是扫描应用的最优边缘地址（host:port）；空 = 用注册信息默认。
     * GUI 扫描页"应用"按钮写入；下次启动生效。
     */
    "edge_addr"?: string;

    /**
     * RulesPath 是路由规则文件路径（相对执行目录解析）。
     */
    "rules_path": string;

    /**
     * GeoDir 是 geosite.dat / geoip-lite.dat 所在目录（相对执行目录解析）。
     */
    "geo_dir": string;

    /**
     * GeoRepo 是 GEO 数据发布仓库；两个下载 URL 由此推导（见 GeoSiteURL/GeoIPURL）。
     */
    "geo_repo": string;

    /**
     * GeoAutoUpdateDays 是 GEO 数据自动更新间隔（天），0 表示关闭。
     */
    "geo_auto_update_days": number;

    /**
     * EnableSystemProxy 控制是否把系统代理指向 mixed 代理端口。
     */
    "enable_system_proxy": boolean;

    /**
     * AllowUDP 控制是否响应 SOCKS5 UDP ASSOCIATE（数据报直连，不经隧道）。
     */
    "allow_udp": boolean;

    /**
     * DownloadProxy 是 GitHub 下载加速前缀（如 https://gh-proxy.org/）。
     * 仅对 GitHub 官方域名（github.com / raw.githubusercontent.com）的下载
     * URL 生效；置空关闭加速。GEO 数据库与默认规则下载共用。
     */
    "download_proxy": string;

    /**
     * DialTimeoutSeconds 是边缘拨号总超时（秒）。仅 Android 使用：装配
     * ctx 的 WithTimeout 值；0 或缺失 = 默认 60s（见 androidDialTimeoutDefault）。
     */
    "dial_timeout_seconds"?: number;

    /**
     * ThemeMode 是界面主题模式：light / dark / system（跟随系统）。
     * GUI 保存设置时同步写入 config.json，启动时从配置读取并注入前端。
     */
    "theme_mode"?: string;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("listen_addr" in $$source)) {
            this["listen_addr"] = "";
        }
        if (!("rules_path" in $$source)) {
            this["rules_path"] = "";
        }
        if (!("geo_dir" in $$source)) {
            this["geo_dir"] = "";
        }
        if (!("geo_repo" in $$source)) {
            this["geo_repo"] = "";
        }
        if (!("geo_auto_update_days" in $$source)) {
            this["geo_auto_update_days"] = 0;
        }
        if (!("enable_system_proxy" in $$source)) {
            this["enable_system_proxy"] = false;
        }
        if (!("allow_udp" in $$source)) {
            this["allow_udp"] = false;
        }
        if (!("download_proxy" in $$source)) {
            this["download_proxy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * RegistrationInfo 是 WARP 注册信息的可序列化视图：与
 * registration.Registration 同字段，但剔除私钥 / 证书等密钥材料，GUI 可安全
 * 展示（id、账号、端点、分配的隧道内地址等）。
 */
export class RegistrationInfo {
    "id": string;
    "account": string;
    "key_type": string;
    "tunnel_type": string;
    "endpoint_v4": string;
    "endpoint_v6": string;
    "endpoint_ports": number[];
    "assigned_ipv4": string;
    "assigned_ipv6": string;

    /** Creates a new RegistrationInfo instance. */
    constructor($$source: Partial<RegistrationInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("key_type" in $$source)) {
            this["key_type"] = "";
        }
        if (!("tunnel_type" in $$source)) {
            this["tunnel_type"] = "";
        }
        if (!("endpoint_v4" in $$source)) {
            this["endpoint_v4"] = "";
        }
        if (!("endpoint_v6" in $$source)) {
            this["endpoint_v6"] = "";
        }
        if (!("endpoint_ports" in $$source)) {
            this["endpoint_ports"] = [];
        }
        if (!("assigned_ipv4" in $$source)) {
            this["assigned_ipv4"] = "";
        }
        if (!("assigned_ipv6" in $$source)) {
            this["assigned_ipv6"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistrationInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RegistrationInfo {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("endpoint_ports" in $$parsedSource) {
            $$parsedSource["endpoint_ports"] = $$createField6_0($$parsedSource["endpoint_ports"]);
        }
        return new RegistrationInfo($$parsedSource as Partial<RegistrationInfo>);
    }
}

/**
 * Status 是 Server 的可序列化快照，供 GUI 轮询展示。不包含任何指针、
 * channel 或可变内部状态 —— 每次调用生成一份拷贝，可安全跨 Wails 绑定
 * 边界传给前端。
 */
export class Status {
    /**
     * stopped | starting | running | stopping
     */
    "state": string;
    "listen_addr"?: string;
    "edge_addrs"?: string[];
    "rules_count": number;
    "geo_ready": boolean;

    /**
     * 系统代理当前是否指向本程序
     */
    "sys_proxy_on": boolean;

    /**
     * 本机是否有可用注册信息
     */
    "registered": boolean;

    /**
     * 运行平台（Android 隐藏系统代理 UI）
     */
    "is_android": boolean;

    /**
     * 基础文件初始化（默认规则/GEO）是否完成，完成后才可启动
     */
    "init_done": boolean;
    "stats": route$0.Stats;
    "start_time"?: string;
    "last_error"?: string;
    "registration"?: RegistrationInfo | null;

    /**
     * 生效中的配置快照
     */
    "config"?: Config | null;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("rules_count" in $$source)) {
            this["rules_count"] = 0;
        }
        if (!("geo_ready" in $$source)) {
            this["geo_ready"] = false;
        }
        if (!("sys_proxy_on" in $$source)) {
            this["sys_proxy_on"] = false;
        }
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }
        if (!("is_android" in $$source)) {
            this["is_android"] = false;
        }
        if (!("init_done" in $$source)) {
            this["init_done"] = false;
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new route$0.Stats());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField2_0 = $$createType1;
        const $$createField9_0 = $$createType2;
        const $$createField12_0 = $$createType4;
        const $$createField13_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edge_addrs" in $$parsedSource) {
            $$parsedSource["edge_addrs"] = $$createField2_0($$parsedSource["edge_addrs"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField9_0($$parsedSource["stats"]);
        }
        if ("registration" in $$parsedSource) {
            $$parsedSource["registration"] = $$createField12_0($$parsedSource["registration"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField13_0($$parsedSource["config"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

/**
 * UpdateInfo 是检查更新的结果。
 */
export class UpdateInfo {
    /**
     * 当前版本（不带 v，如 0.5.3）
     */
    "current": string;

    /**
     * 最新版本（不带 v）
     */
    "latest": string;
    "has_update": boolean;

    /**
     * 最新 Release 页面（浏览器打开下载）
     */
    "url": string;

    /**
     * 最新 tag（带 v，如 v0.5.3）
     */
    "tag": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("has_update" in $$source)) {
            this["has_update"] = false;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = route$0.Stats.createFrom;
const $$createType3 = RegistrationInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = Config.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
