// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GeoInfo 是 GEO 页展示的数据快照。
 */
export class GeoInfo {
    "geosite_path": string;
    "geoip_path": string;
    "geosite_updated"?: string;
    "geoip_updated"?: string;
    "repository": string;
    "base_url": string;
    "auto_update_days": number;
    "last_checked"?: string;

    /** Creates a new GeoInfo instance. */
    constructor($$source: Partial<GeoInfo> = {}) {
        if (!("geosite_path" in $$source)) {
            this["geosite_path"] = "";
        }
        if (!("geoip_path" in $$source)) {
            this["geoip_path"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("auto_update_days" in $$source)) {
            this["auto_update_days"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeoInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GeoInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeoInfo($$parsedSource as Partial<GeoInfo>);
    }
}

/**
 * LogEntry 是日志页展示的单条记录。
 */
export class LogEntry {
    "time": string;

    /**
     * info | warn | error | debug
     */
    "level": string;
    "msg": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("msg" in $$source)) {
            this["msg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

/**
 * UpdateGeoResult 是手动更新 GEO 的结果。
 */
export class UpdateGeoResult {
    "ok": boolean;
    "message": string;

    /** Creates a new UpdateGeoResult instance. */
    constructor($$source: Partial<UpdateGeoResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateGeoResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateGeoResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateGeoResult($$parsedSource as Partial<UpdateGeoResult>);
    }
}
