// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 持有 core.Server 的惰性实例。GUI 打开时不必立即启动代理：
 * 服务方法在需要时才创建/使用 Server。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyEdge 应用扫描选出的最优边缘地址（写入 config.json，下次启动生效）。
 */
export function ApplyEdge(addr: string): $CancellablePromise<void> {
    return $Call.ByID(3886576470, addr);
}

/**
 * CheckUpdate 查询 GitHub Releases 最新版本并返回更新信息。
 * 网络失败返回错误（前端显示"检查失败"，非致命）；dev 版本不参与比较
 * （永远提示可更新，引导用户装正式版）。
 */
export function CheckUpdate(): $CancellablePromise<core$0.UpdateInfo | null> {
    return $Call.ByID(1914844742).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClearLogs 清空日志环形缓冲（日志页"清空"按钮调用）。
 * 此前前端只清了本地 state，后端缓冲不变——轮询下一帧旧日志又回来。
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(2596992753);
}

/**
 * Deregister 注销并删除本地注册。
 */
export function Deregister(): $CancellablePromise<void> {
    return $Call.ByID(2794352299);
}

/**
 * GetAutostartEnabled 报告开机自启状态。
 */
export function GetAutostartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2581917369);
}

/**
 * GetConfig 返回当前生效配置（前端设置页表单数据源）。
 */
export function GetConfig(): $CancellablePromise<core$0.Config> {
    return $Call.ByID(1122024869).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetGeo 返回 GEO 数据库状态。
 */
export function GetGeo(): $CancellablePromise<$models.GeoInfo> {
    return $Call.ByID(1332817872).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetLogs 返回最近 limit 条日志（环形缓冲，logs.go）。
 */
export function GetLogs(limit: number): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(2910743932, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetRules 返回 rules.txt 当前完整文本（前端逐行展示/编辑）。
 */
export function GetRules(): $CancellablePromise<string> {
    return $Call.ByID(3551143166);
}

/**
 * GetStatus 返回当前状态快照。
 */
export function GetStatus(): $CancellablePromise<core$0.Status> {
    return $Call.ByID(1244446001).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetSystemProxyEnabled 报告系统代理当前是否指向本程序。
 */
export function GetSystemProxyEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(348895343);
}

/**
 * GetVersion 返回构建版本（前端设置页展示）。版本号经 ldflags 注入，
 * 与 release tag 同源；本地构建返回 "dev"。
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(307981769);
}

/**
 * InitDefaults 初始化基础文件（rules.txt 下载/模板 + GEO 下载，不依赖注册）。
 * GUI 首次启动时调用；幂等，可安全重复。完成后日志打出"初始化完成"，
 * GetStatus.InitDone 置 true（前端据此在初始化完成前禁用启动按钮）。
 */
export function InitDefaults(): $CancellablePromise<void> {
    return $Call.ByID(4037609349);
}

/**
 * IsRunning 报告代理是否运行中。
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3694497516);
}

/**
 * OpenExternalBrowser 用系统浏览器打开 URL（更新下载页等）。
 * 桌面端走 Wails BrowserManager（调系统默认浏览器）；Android 走反向 JNI 桥
 * 跳第三方浏览器——WebView 内 target=_blank 会被应用内捕获，GitHub 下载页
 * 在 WebView 里体验差/登录墙（v0.5.11 反馈）。
 */
export function OpenExternalBrowser(url: string): $CancellablePromise<void> {
    return $Call.ByID(2069720938, url);
}

/**
 * Register 执行 WARP 注册（幂等；已有注册则报告 existing=true）。
 */
export function Register(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(4131014992);
}

/**
 * ReloadRules 从磁盘重新加载规则。
 */
export function ReloadRules(): $CancellablePromise<void> {
    return $Call.ByID(3431277955);
}

/**
 * SaveConfig 校验并保存配置；写入即生效（内存快照同步），无需重启。
 */
export function SaveConfig(cfg: core$0.Config): $CancellablePromise<void> {
    return $Call.ByID(3855370806, cfg);
}

/**
 * SaveRules 校验并写回 rules.txt（引擎热重载自动生效）。
 */
export function SaveRules(rulesText: string): $CancellablePromise<void> {
    return $Call.ByID(1454794991, rulesText);
}

/**
 * ScanEdges 扫描 WARP 边缘，返回最优端点列表（GUI "扫描最优边缘"按钮）。
 */
export function ScanEdges(): $CancellablePromise<string[]> {
    return $Call.ByID(2023048538).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ScanEdgesV4 扫描 IPv4 边缘。
 */
export function ScanEdgesV4(): $CancellablePromise<string[]> {
    return $Call.ByID(3594054256).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ScanEdgesV6 扫描 IPv6 边缘。
 */
export function ScanEdgesV6(): $CancellablePromise<string[]> {
    return $Call.ByID(3627609494).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SetAutostart 开启/关闭开机自启。
 */
export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(241102900, enabled);
}

/**
 * SetSystemProxy 开启/关闭系统代理（指向当前监听地址）。
 * 开启且内核未运行时自动启动代理内核（用户需求：开启系统代理即启动
 * warp-go）。未注册时 Start 会报错并记录到 startErr/日志，不会挂起。
 */
export function SetSystemProxy(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2842820918, enabled);
}

/**
 * Start 启动代理（幂等：已在运行则无操作）。
 * 
 * Android 上直接桥接 VpnService（反向 JNI，见 androidbridge.go）；桌面走
 * core.Server.Start（阻塞设计，GUI 里必须在 goroutine 中异步启动）。
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1681485135);
}

/**
 * Stop 停止代理（幂等）。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3775538709);
}

/**
 * UpdateGeo 立即更新 GEO 数据库。
 */
export function UpdateGeo(): $CancellablePromise<$models.UpdateGeoResult> {
    return $Call.ByID(1224723457).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = core$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = core$0.Config.createFrom;
const $$createType3 = $models.GeoInfo.createFrom;
const $$createType4 = $models.LogEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = core$0.Status.createFrom;
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = $models.UpdateGeoResult.createFrom;
