// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Stats 是匹配引擎的命中计数快照（GUI 状态展示用）。
 * json tag 与前端 ProxyCounters 键对齐（proxy/direct/rejected/miss），
 * 生成 bindings 时 TS 属性名即为此 tag（见 frontend/bindings/warp/route/models.ts）。
 */
export class Stats {
    /**
     * 命中 proxy 规则的次数
     */
    "proxy": number;

    /**
     * 命中 direct 规则的次数
     */
    "direct": number;

    /**
     * 命中 reject 规则的次数（被拦截的连接）
     */
    "rejected": number;

    /**
     * 未命中任何规则的次数（隐式 direct 兜底）
     */
    "miss": number;

    /** Creates a new Stats instance. */
    constructor($$source: Partial<Stats> = {}) {
        if (!("proxy" in $$source)) {
            this["proxy"] = 0;
        }
        if (!("direct" in $$source)) {
            this["direct"] = 0;
        }
        if (!("rejected" in $$source)) {
            this["rejected"] = 0;
        }
        if (!("miss" in $$source)) {
            this["miss"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     */
    static createFrom($$source: any = {}): Stats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats($$parsedSource as Partial<Stats>);
    }
}
