// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppProfiles 是 profiles.json 的顶层结构。
 */
export class AppProfiles {
    "active_profile": string;
    "profiles": XTunnelProfile[];

    /**
     * GhProxy 是 GitHub 加速下载前缀（东哥 09-05 反馈④），用于 GEO 数据库
     * 与检查更新等 GitHub 下载。空 = 默认 https://gh-proxy.org；"off" = 直连。
     */
    "gh_proxy"?: string;

    /** Creates a new AppProfiles instance. */
    constructor($$source: Partial<AppProfiles> = {}) {
        if (!("active_profile" in $$source)) {
            this["active_profile"] = "";
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppProfiles instance from a string or object.
     */
    static createFrom($$source: any = {}): AppProfiles {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField1_0($$parsedSource["profiles"]);
        }
        return new AppProfiles($$parsedSource as Partial<AppProfiles>);
    }
}

/**
 * GeoInfo 是 GEO 页展示快照。
 */
export class GeoInfo {
    "geosite_path": string;
    "geoip_path": string;
    "geosite_updated"?: string;
    "geoip_updated"?: string;
    "repository": string;
    "base_url": string;

    /** Creates a new GeoInfo instance. */
    constructor($$source: Partial<GeoInfo> = {}) {
        if (!("geosite_path" in $$source)) {
            this["geosite_path"] = "";
        }
        if (!("geoip_path" in $$source)) {
            this["geoip_path"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeoInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GeoInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeoInfo($$parsedSource as Partial<GeoInfo>);
    }
}

/**
 * InitState 是启动初始化进度快照。
 */
export class InitState {
    /**
     * idle|downloading|done|failed
     */
    "state": string;

    /**
     * 正在下载的文件
     */
    "current"?: string;

    /**
     * 0-100
     */
    "progress"?: number;

    /**
     * 失败原因
     */
    "error"?: string;

    /** Creates a new InitState instance. */
    constructor($$source: Partial<InitState> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitState instance from a string or object.
     */
    static createFrom($$source: any = {}): InitState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InitState($$parsedSource as Partial<InitState>);
    }
}

/**
 * LogEntry 是日志页展示的单条记录。
 */
export class LogEntry {
    "time": string;

    /**
     * info | warn | error | debug
     */
    "level": string;
    "msg": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("msg" in $$source)) {
            this["msg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

/**
 * Status 是前端状态快照（GetStatus 返回）。
 */
export class Status {
    "state": string;
    "listen_addr": string;
    "control_url": string;
    "version": string;
    "last_error": string;
    "started_at": string;
    "sys_proxy_on": boolean;
    "init_done": boolean;

    /**
     * sidecar 二进制在位
     */
    "sidecar_ok": boolean;

    /**
     * 当前激活配置名
     */
    "active_name": string;

    /**
     * 已配置服务器
     */
    "configured": boolean;
    "route_enabled"?: boolean;
    "rule_count"?: number;
    "proxy_hits"?: number;
    "direct_hits"?: number;
    "rejected_hits"?: number;
    "site_loaded"?: boolean;
    "ip_loaded"?: boolean;
    "bytes_sent"?: number;
    "bytes_recv"?: number;

    /**
     * 启动初始化（GEO 下载）进度
     */
    "init": InitState;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("listen_addr" in $$source)) {
            this["listen_addr"] = "";
        }
        if (!("control_url" in $$source)) {
            this["control_url"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("last_error" in $$source)) {
            this["last_error"] = "";
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "";
        }
        if (!("sys_proxy_on" in $$source)) {
            this["sys_proxy_on"] = false;
        }
        if (!("init_done" in $$source)) {
            this["init_done"] = false;
        }
        if (!("sidecar_ok" in $$source)) {
            this["sidecar_ok"] = false;
        }
        if (!("active_name" in $$source)) {
            this["active_name"] = "";
        }
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("init" in $$source)) {
            this["init"] = (new InitState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField20_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("init" in $$parsedSource) {
            $$parsedSource["init"] = $$createField20_0($$parsedSource["init"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

/**
 * UpdateGeoResult 是手动更新 GEO 的结果。
 */
export class UpdateGeoResult {
    "ok": boolean;
    "message": string;

    /** Creates a new UpdateGeoResult instance. */
    constructor($$source: Partial<UpdateGeoResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateGeoResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateGeoResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateGeoResult($$parsedSource as Partial<UpdateGeoResult>);
    }
}

/**
 * UpdateInfo 是检查更新结果。
 */
export class UpdateInfo {
    "has_update": boolean;
    "latest": string;
    "current": string;
    "url": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("has_update" in $$source)) {
            this["has_update"] = false;
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

/**
 * XTunnelProfile 是 GUI 管理的一个服务器配置（对齐 Android XTunnelProfile 全字段）。
 */
export class XTunnelProfile {
    "name": string;

    /**
     * wss://host:port[/path] 或 ws://
     */
    "server_url": string;
    "token": string;

    /**
     * socks5://127.0.0.1:11080
     */
    "local_listen": string;

    /**
     * 路由 CIDR（空=默认）
     */
    "cidr": string;

    /**
     * 自定义 DNS（空=默认）
     */
    "dns": string;

    /**
     * ECH 域名（空=默认 cloudflare-ech.com）
     */
    "ech": string;

    /**
     * UDP 阻断端口，如 "443"
     */
    "block_ports": string;

    /**
     * 每 IP 连接数
     */
    "connections": number;
    "insecure": boolean;
    "fallback": boolean;

    /**
     * -ip CF 优选 IP/域名，逗号分隔
     */
    "dial_ips": string;

    /**
     * 4|6|4,6|6,4
     */
    "ip_strategy": string;
    "dns_cache_ttl": string;

    /** Creates a new XTunnelProfile instance. */
    constructor($$source: Partial<XTunnelProfile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("server_url" in $$source)) {
            this["server_url"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("local_listen" in $$source)) {
            this["local_listen"] = "";
        }
        if (!("cidr" in $$source)) {
            this["cidr"] = "";
        }
        if (!("dns" in $$source)) {
            this["dns"] = "";
        }
        if (!("ech" in $$source)) {
            this["ech"] = "";
        }
        if (!("block_ports" in $$source)) {
            this["block_ports"] = "";
        }
        if (!("connections" in $$source)) {
            this["connections"] = 0;
        }
        if (!("insecure" in $$source)) {
            this["insecure"] = false;
        }
        if (!("fallback" in $$source)) {
            this["fallback"] = false;
        }
        if (!("dial_ips" in $$source)) {
            this["dial_ips"] = "";
        }
        if (!("ip_strategy" in $$source)) {
            this["ip_strategy"] = "";
        }
        if (!("dns_cache_ttl" in $$source)) {
            this["dns_cache_ttl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new XTunnelProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): XTunnelProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new XTunnelProfile($$parsedSource as Partial<XTunnelProfile>);
    }
}

// Private type creation functions
const $$createType0 = XTunnelProfile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = InitState.createFrom;
