// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 持有 sidecar 管理器与配置目录。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveProfile 返回激活配置（无配置返回 nil 不报错）。
 */
export function ActiveProfile(): $CancellablePromise<$models.XTunnelProfile | null> {
    return $Call.ByID(863259216).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckUpdate 查询 GitHub Releases 最新版本（GUI 仓库）。
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(1914844742).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ClearLogs 清空日志环。
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(2596992753);
}

/**
 * ExportDiagnostics 导出诊断包到用户下载目录，返回文件绝对路径。
 * 内容：diagnostics.json（状态/GEO/流量/进程）+ logs.txt（GUI 日志环）+
 * sidecar.log 尾部。失败返回空串与错误。
 */
export function ExportDiagnostics(): $CancellablePromise<string> {
    return $Call.ByID(3428609321);
}

/**
 * GetAutostartEnabled 查询自启状态。
 */
export function GetAutostartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2581917369);
}

/**
 * GetGeo 返回 GEO 数据库状态。
 */
export function GetGeo(): $CancellablePromise<$models.GeoInfo> {
    return $Call.ByID(1332817872).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetLogs 返回日志环（最近 limit 条）。
 */
export function GetLogs(limit: number): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(2910743932, limit).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetRules 读 rules.txt。
 */
export function GetRules(): $CancellablePromise<string> {
    return $Call.ByID(3551143166);
}

/**
 * GetStatus 返回状态快照。
 */
export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(1244446001).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetSystemProxyEnabled 报告系统代理当前是否开启（指向本地任一激活监听）。
 */
export function GetSystemProxyEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(348895343);
}

/**
 * GetVersion 返回 GUI 版本号（单源：CI 注入；见 version.go）。
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(307981769);
}

/**
 * InitDefaults 初始化 GEO 数据库（幂等；失败不阻塞 GUI，状态页可手动重试）。
 */
export function InitDefaults(): $CancellablePromise<void> {
    return $Call.ByID(4037609349);
}

/**
 * IsRunning 报告 sidecar 是否运行中。
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3694497516);
}

/**
 * ListProfiles 返回全部配置与激活名。
 */
export function ListProfiles(): $CancellablePromise<$models.AppProfiles> {
    return $Call.ByID(3030445699).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * OpenExternalBrowser 用系统默认浏览器打开 URL。
 */
export function OpenExternalBrowser(url: string): $CancellablePromise<void> {
    return $Call.ByID(2069720938, url);
}

/**
 * ReloadRules 触发 sidecar 热重载（control POST /v1/route/reload）。
 */
export function ReloadRules(): $CancellablePromise<void> {
    return $Call.ByID(3431277955);
}

/**
 * SaveProfiles 保存配置列表与激活项（前端编辑后整体回写；逐条校验）。
 */
export function SaveProfiles(p: $models.AppProfiles): $CancellablePromise<void> {
    return $Call.ByID(1208366826, p);
}

/**
 * SaveRules 校验并写回 rules.txt。
 * 语法校验走 sidecar 的规则解析（M1 先做行格式基本校验，M3 接 control 热重载）。
 */
export function SaveRules(rulesText: string): $CancellablePromise<void> {
    return $Call.ByID(1454794991, rulesText);
}

/**
 * SetAutostart 开关开机自启（Windows 注册表 Run 键）。
 */
export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(241102900, enabled);
}

/**
 * SetSystemProxy 开启/关闭系统代理（指向激活配置的本地监听）。
 * 开启且未运行时自动启动。
 */
export function SetSystemProxy(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2842820918, enabled);
}

/**
 * SidecarLog 返回 sidecar 日志尾部（诊断用）。
 */
export function SidecarLog(limit: number): $CancellablePromise<string> {
    return $Call.ByID(2270661234, limit);
}

/**
 * Start 启动 sidecar（用激活配置合成 config.json；幂等）。
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1681485135);
}

/**
 * Stop 停止 sidecar 并还原系统代理（幂等）。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3775538709);
}

/**
 * UpdateGeo 立即更新 GEO 数据库（下载走系统直连）。
 */
export function UpdateGeo(): $CancellablePromise<$models.UpdateGeoResult> {
    return $Call.ByID(1224723457).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = $models.XTunnelProfile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.UpdateInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GeoInfo.createFrom;
const $$createType5 = $models.LogEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.Status.createFrom;
const $$createType8 = $models.AppProfiles.createFrom;
const $$createType9 = $models.UpdateGeoResult.createFrom;
